# Generated by Django 4.0.1 on 2022-01-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speak',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
