# Generated by Django 3.2.8 on 2022-01-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speak', '0002_speak_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speak',
            options={'ordering': ['-id']},
        ),
    ]
